<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { useMapStore } from '../../stores/mapStore'
import { useLineupStore } from '../../stores/lineupStore'
import { useThemeStore } from '../../stores/themeStore'
import { useCs2ServerStore } from '../../stores/cs2ServerStore'
import { pctToWorldCoords, generateSetposCommand } from '../../utils/cs2Coords'
import { captureScreenFrame, extractImageFromClipboard } from '../../utils/screenCapture'
import { 
  X, 
  Gamepad2, 
  Download, 
  Copy, 
  Check, 
  Terminal, 
  Server, 
  Layers, 
  Radio, 
  Sparkles, 
  Sliders, 
  HelpCircle, 
  ExternalLink, 
  Code2, 
  Play, 
  RotateCcw, 
  Zap, 
  Camera, 
  Upload, 
  Image as ImageIcon, 
  CheckCircle2, 
  AlertCircle, 
  RefreshCw, 
  Trash2,
  Monitor,
  Cpu,
  ShieldAlert,
  Clipboard,
  FileCode2,
  FolderOpen,
  Eye,
  Video,
  Film
} from 'lucide-vue-next'

const props = defineProps<{
  isOpen: boolean
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

const mapStore = useMapStore()
const lineupStore = useLineupStore()
const themeStore = useThemeStore()
const cs2ServerStore = useCs2ServerStore()

const activeTab = ref<'cfg' | 'setpos' | 'dedicated'>('cfg')
const copiedCfg = ref(false)
const copiedDocker = ref(false)
const copiedSetpos = ref(false)
const copiedServerSetpos = ref(false)
const copiedWindowsInstaller = ref(false)
const copiedWindowsStart = ref(false)

// ── DEDICATED HOSTING PLATFORM ──────────────────────────────
const serverHostingPlatform = ref<'windows' | 'docker'>('windows')
const approvedWindowsSelfInstall = ref(false)

// ── PRACTICE CFG OPTIONS ────────────────────────────────────
const cfgOptions = reactive({
  grenadeCamera: true,          // sv_grenade_trajectory_prac_pipreview 1
  grenadePreview: true,         // cl_grenadepreview 1
  trajectoryTrailTime: 15,      // sv_grenade_trajectory_prac_trailtime 15
  showImpacts: true,            // sv_showimpacts 1
  infiniteAmmo: true,           // sv_infinite_ammo 1
  buyAnywhere: true,            // mp_buy_anywhere 1
  infiniteBuyTime: true,        // mp_buytime 60000
  longRoundTime: true,          // mp_roundtime_defuse 60
  kickBots: true,               // bot_kick
  godMode: true,                // sv_regeneration_force_on 1
  
  // Custom Keybinds
  bindNoclip: 'alt',
  bindRethrow: 'h',
  bindClearNades: 'c',
  bindPlaceBot: 'p',
  bindFastForward: 't'
})

// ── DEDICATED SERVER CONFIG ────────────────────────────────
const dedicatedConfig = reactive({
  serverName: 'Protutech Tactical Practice',
  serverPort: 27015,
  rconPassword: 'change_this_rcon_pass',
  startMap: 'de_mirage',
  maxPlayers: 10,
  tickrate: 128
})

// ── SETPOS TELEPORT SELECTOR ────────────────────────────────
const selectedMapForSetpos = ref(mapStore.currentMapId || 'mirage')
const selectedLineupId = ref<string>('')

const availableLineupsForMap = computed(() => {
  return lineupStore.allLineups.filter(l => l.mapId === selectedMapForSetpos.value)
})

const currentSetposCommand = computed(() => {
  const l = lineupStore.allLineups.find(x => x.id === selectedLineupId.value)
  if (l && l.originCoords) {
    return generateSetposCommand(selectedMapForSetpos.value, l.originCoords)
  }
  // Default map center
  const world = pctToWorldCoords(selectedMapForSetpos.value, { x: 50, y: 50 })
  return `setpos_exact ${world.x} ${world.y} ${world.z}; setang 0 0 0`
})

// ── GENERATE FULL PRACTICE.CFG SCRIPT ───────────────────────
const generatedCfgScript = computed(() => {
  const lines: string[] = [
    '// ============================================================',
    '// CS2 PRACTICE & LINEUP SERVER CONFIGURATION',
    '// Generated by Protutech CS2 Nades (https://github.com/IAndrexI/CS2Nades)',
    '// ============================================================',
    '',
    '// Enable cheats & basic server environment',
    'sv_cheats 1',
    cfgOptions.kickBots ? 'bot_kick' : '// bot_kick',
    'mp_warmup_end',
    'mp_freezetime 0',
    cfgOptions.longRoundTime ? 'mp_roundtime 60\nmp_roundtime_defuse 60\nmp_roundtime_hostage 60' : 'mp_roundtime_defuse 2',
    'mp_maxmoney 65535',
    'mp_startmoney 65535',
    'mp_afterroundmoney 65535',
    cfgOptions.infiniteBuyTime ? 'mp_buytime 60000' : 'mp_buytime 90',
    cfgOptions.buyAnywhere ? 'mp_buy_anywhere 1' : 'mp_buy_anywhere 0',
    '',
    '// Tactical Grenade & Ammo Physics',
    cfgOptions.infiniteAmmo ? 'sv_infinite_ammo 1' : 'sv_infinite_ammo 0',
    'ammo_grenade_limit_total 6',
    'ammo_grenade_limit_flashbang 2',
    'mp_drop_knife_enable 1',
    'mp_drop_grenade_enable 1',
    '',
    '// Grenade Trajectory Tools & Cameras',
    cfgOptions.grenadeCamera ? 'sv_grenade_trajectory_prac_pipreview 1' : 'sv_grenade_trajectory_prac_pipreview 0',
    `sv_grenade_trajectory_prac_trailtime ${cfgOptions.trajectoryTrailTime}`,
    cfgOptions.grenadePreview ? 'cl_grenadepreview 1' : 'cl_grenadepreview 0',
    cfgOptions.showImpacts ? 'sv_showimpacts 1' : 'sv_showimpacts 0',
    cfgOptions.godMode ? 'sv_regeneration_force_on 1' : 'sv_regeneration_force_on 0',
    '',
    '// Tactical Keybinds (Customized)',
  ]

  if (cfgOptions.bindNoclip.trim()) {
    lines.push(`bind "${cfgOptions.bindNoclip.trim()}" "noclip"`)
  }
  if (cfgOptions.bindRethrow.trim()) {
    lines.push(`bind "${cfgOptions.bindRethrow.trim()}" "sv_rethrow_last_grenade"`)
  }
  if (cfgOptions.bindClearNades.trim()) {
    lines.push(`bind "${cfgOptions.bindClearNades.trim()}" "ent_fire smokegrenade_projectile kill; ent_fire molotov_projectile kill; ent_fire flashbang_projectile kill; ent_fire hegrenade_projectile kill; ent_fire decoyprojectile kill; stopsound"`)
  }
  if (cfgOptions.bindPlaceBot.trim()) {
    lines.push(`bind "${cfgOptions.bindPlaceBot.trim()}" "bot_place; bot_stop 1; bot_dont_shoot 1"`)
  }
  if (cfgOptions.bindFastForward.trim()) {
    lines.push(`bind "${cfgOptions.bindFastForward.trim()}" "toggle host_timescale 1 5"`)
  }

  lines.push('')
  lines.push('// Restart match with practice rules')
  lines.push('mp_restartgame 1')
  lines.push('echo "==============================================="')
  lines.push('echo ">>> PROTUTECH CS2 PRACTICE CONFIG LOADED! <<<"')
  lines.push('echo "==============================================="')

  return lines.join('\n')
})

// ── GENERATE DEDICATED DOCKER-COMPOSE ───────────────────────
const generatedDockerCompose = computed(() => {
  return `version: '3.8'

services:
  cs2-practice-server:
    image: joedwards32/cs2
    container_name: cs2-practice-server
    restart: unless-stopped
    environment:
      - SERVER_NAME=${dedicatedConfig.serverName}
      - SERVER_PASSWORD=
      - RCON_PASSWORD=${dedicatedConfig.rconPassword}
      - START_MAP=${dedicatedConfig.startMap}
      - MAXPLAYERS=${dedicatedConfig.maxPlayers}
      - TICKRATE=${dedicatedConfig.tickrate}
      - GAME_TYPE=0
      - GAME_MODE=1
      - MAPGROUP=mg_active
    ports:
      - "${dedicatedConfig.serverPort}:${dedicatedConfig.serverPort}/tcp"
      - "${dedicatedConfig.serverPort}:${dedicatedConfig.serverPort}/udp"
    volumes:
      - cs2-server-data:/home/steam/cs2-dedicated`
})

// ── GENERATE WINDOWS DEDICATED SERVER SELF-INSTALLER ─────────
const generatedWindowsInstallerScript = computed(() => {
  const p = dedicatedConfig.serverPort || 27015
  const map = dedicatedConfig.startMap || 'de_mirage'
  const pass = dedicatedConfig.rconPassword || 'cs2practice'
  const name = dedicatedConfig.serverName || 'CS2 Local Practice Server'

  return `@echo off
title CS2 Dedicated Server - Windows Auto Installer
color 0A
echo =======================================================================
echo  [CS2 Nades] Windows Local Dedicated Server Installer & Auto-Setup
echo =======================================================================
echo.
echo Target Installation Directory: C:\\CS2_Dedicated_Server
echo.
mkdir C:\\CS2_Dedicated_Server\\steamcmd 2>nul
mkdir C:\\CS2_Dedicated_Server\\cs2 2>nul

echo [1/4] Downloading SteamCMD client...
powershell -Command "Invoke-WebRequest -Uri 'https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip' -OutFile 'C:\\CS2_Dedicated_Server\\steamcmd\\steamcmd.zip'"
powershell -Command "Expand-Archive -Path 'C:\\CS2_Dedicated_Server\\steamcmd\\steamcmd.zip' -DestinationPath 'C:\\CS2_Dedicated_Server\\steamcmd' -Force"
del C:\\CS2_Dedicated_Server\\steamcmd\\steamcmd.zip 2>nul

echo.
echo [2/4] Downloading Counter-Strike 2 Dedicated Server (App ID 730)...
echo (This will download ~30-35 GB directly from Steam servers. Please be patient...)
C:\\CS2_Dedicated_Server\\steamcmd\\steamcmd.exe +force_install_dir C:\\CS2_Dedicated_Server\\cs2 +login anonymous +app_update 730 validate +quit

echo.
echo [3/4] Installing Practice Config & Rules...
mkdir "C:\\CS2_Dedicated_Server\\cs2\\game\\csgo\\cfg" 2>nul
(
echo // CS2 Nades Practice Configuration
echo sv_cheats 1
echo bot_kick
echo mp_warmup_end
echo mp_freezetime 0
echo mp_roundtime_defuse 60
echo mp_maxmoney 65535
echo mp_startmoney 65535
echo mp_afterroundmoney 65535
echo mp_buytime 60000
echo mp_buy_anywhere 1
echo sv_infinite_ammo 1
echo ammo_grenade_limit_total 6
echo sv_grenade_trajectory_prac_pipreview 1
echo sv_grenade_trajectory_prac_trailtime 15
echo cl_grenadepreview 1
echo sv_showimpacts 1
echo sv_regeneration_force_on 1
echo bind "alt" "noclip"
echo bind "h" "sv_rethrow_last_grenade"
echo mp_restartgame 1
) > "C:\\CS2_Dedicated_Server\\cs2\\game\\csgo\\cfg\\practice.cfg"

echo.
echo [4/4] Generating Server Start Launcher (start_server.bat)...
(
echo @echo off
echo title CS2 Dedicated Practice Server - ${name}
echo cd /d "C:\\CS2_Dedicated_Server\\cs2\\game\\bin\\win64"
echo cs2.exe -dedicated -console +ip 0.0.0.0 -port ${p} +map ${map} +game_type 0 +game_mode 1 +mapgroup mg_active +sv_cheats 1 +rcon_password "${pass}" +exec practice.cfg
) > "C:\\CS2_Dedicated_Server\\start_server.bat"

echo.
echo =======================================================================
echo  SUCCESS! CS2 Dedicated Server is now fully installed on your PC.
echo  To launch your server anytime, double-click:
echo  C:\\CS2_Dedicated_Server\\start_server.bat
echo =======================================================================
pause`
})

const generatedWindowsStartScript = computed(() => {
  const p = dedicatedConfig.serverPort || 27015
  const map = dedicatedConfig.startMap || 'de_mirage'
  const pass = dedicatedConfig.rconPassword || 'cs2practice'
  const name = dedicatedConfig.serverName || 'CS2 Local Practice Server'

  return `@echo off
title CS2 Dedicated Practice Server - ${name}
cd /d "C:\\CS2_Dedicated_Server\\cs2\\game\\bin\\win64"
echo Starting CS2 Dedicated Server on Port ${p} (Map: ${map})...
cs2.exe -dedicated -console +ip 0.0.0.0 -port ${p} +map ${map} +game_type 0 +game_mode 1 +mapgroup mg_active +sv_cheats 1 +rcon_password "${pass}" +exec practice.cfg
pause`
})

function handleDownloadWindowsInstaller() {
  downloadFile('install_cs2_server_windows.bat', generatedWindowsInstallerScript.value)
}

function handleDownloadWindowsStart() {
  downloadFile('start_cs2_server.bat', generatedWindowsStartScript.value)
}

// ── ACTION HANDLERS ─────────────────────────────────────────
function downloadFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function handleDownloadCfg() {
  downloadFile('practice.cfg', generatedCfgScript.value)
}

async function copyToClipboard(text: string, type: 'cfg' | 'docker' | 'setpos' | 'serverSetpos' | 'windowsInstaller' | 'windowsStart') {
  try {
    await navigator.clipboard.writeText(text)
    if (type === 'cfg') {
      copiedCfg.value = true
      setTimeout(() => (copiedCfg.value = false), 2500)
    } else if (type === 'docker') {
      copiedDocker.value = true
      setTimeout(() => (copiedDocker.value = false), 2500)
    } else if (type === 'setpos') {
      copiedSetpos.value = true
      setTimeout(() => (copiedSetpos.value = false), 2500)
    } else if (type === 'serverSetpos') {
      copiedServerSetpos.value = true
      setTimeout(() => (copiedServerSetpos.value = false), 2500)
    } else if (type === 'windowsInstaller') {
      copiedWindowsInstaller.value = true
      setTimeout(() => (copiedWindowsInstaller.value = false), 2500)
    } else if (type === 'windowsStart') {
      copiedWindowsStart.value = true
      setTimeout(() => (copiedWindowsStart.value = false), 2500)
    }
  } catch (err) {
    console.error('Failed to copy', err)
  }
}
</script>

<template>
  <Teleport to="body">
    <div
      v-if="isOpen"
      class="fixed inset-0 bg-black/85 backdrop-blur-md overflow-y-auto p-3 sm:p-6 flex items-center justify-center animate-fade-in"
      style="z-index: 9999999 !important;"
      @click.self="emit('close')"
    >
      <div 
        class="relative w-full max-w-4xl border border-slate-700/80 rounded-3xl shadow-2xl overflow-hidden flex flex-col my-auto max-h-[92vh] sm:max-h-[86vh]"
        :style="{ backgroundColor: themeStore.customModalBgColor }"
      >
        <!-- HEADER -->
        <div class="p-5 border-b border-slate-800 bg-slate-950/90 flex flex-wrap items-center justify-between gap-4 shrink-0">
          <div class="flex items-center gap-3">
            <div 
              class="p-2.5 rounded-2xl border shadow-inner flex items-center justify-center"
              :style="{ backgroundColor: themeStore.customAccentColor + '22', borderColor: themeStore.customAccentColor + '66', color: themeStore.customAccentColor }"
            >
              <Gamepad2 class="w-6 h-6 stroke-[2.5]" />
            </div>
            <div>
              <div class="flex items-center gap-2">
                <h2 class="text-base font-black uppercase text-white tracking-wide">
                  CS2 Server Sync & Practice Studio
                </h2>
                <span class="px-2 py-0.5 rounded bg-amber-500/20 text-amber-400 text-[10px] font-mono font-black uppercase tracking-wider flex items-center gap-1">
                  <Zap class="w-3 h-3 fill-current" />
                  Auto-Sync & Capture
                </span>
              </div>
              <p class="text-xs text-slate-400 mt-0.5">
                Auto-sync lineups and screenshots with your self-hosted/private CS2 server, generate practice scripts, and teleport.
              </p>
            </div>
          </div>

          <!-- TAB SWITCHER -->
          <div class="flex items-center gap-1 p-1 bg-slate-900/90 rounded-xl border border-slate-800 flex-wrap">

            <button
              @click="activeTab = 'cfg'"
              :class="[
                'px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5',
                activeTab === 'cfg' ? 'font-black shadow' : 'text-slate-400 hover:text-white'
              ]"
              :style="activeTab === 'cfg' ? { backgroundColor: themeStore.customAccentColor, color: '#020617' } : {}"
            >
              <Terminal class="w-3.5 h-3.5" />
              <span>Practice CFG</span>
            </button>

            <button
              @click="activeTab = 'setpos'"
              :class="[
                'px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5',
                activeTab === 'setpos' ? 'font-black shadow' : 'text-slate-400 hover:text-white'
              ]"
              :style="activeTab === 'setpos' ? { backgroundColor: themeStore.customAccentColor, color: '#020617' } : {}"
            >
              <Sliders class="w-3.5 h-3.5" />
              <span>Teleport Binds</span>
            </button>

            <button
              @click="activeTab = 'dedicated'"
              :class="[
                'px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5',
                activeTab === 'dedicated' ? 'font-black shadow' : 'text-slate-400 hover:text-white'
              ]"
              :style="activeTab === 'dedicated' ? { backgroundColor: themeStore.customAccentColor, color: '#020617' } : {}"
            >
              <Server class="w-3.5 h-3.5" />
              <span>Dedicated Server</span>
            </button>

            <button 
              @click="emit('close')" 
              class="text-slate-400 hover:text-white p-1.5 rounded-lg hover:bg-slate-800 transition-colors cursor-pointer ml-1"
            >
              <X class="w-4 h-4" />
            </button>
          </div>
        </div>


        <!-- BODY CONTENT -->
        <div class="flex-1 overflow-y-auto p-5 sm:p-6 flex flex-col gap-6 text-xs scrollbar-thin">
          
          <!-- ============================================================ -->
          <!-- TAB 1: PRACTICE CFG BUILDER -->
          <!-- ============================================================ -->
          <div v-if="activeTab === 'cfg'" class="flex flex-col gap-6">
            <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
              <!-- LEFT: TOGGLE CONTROLS -->
              <div class="lg:col-span-7 flex flex-col gap-4">
                <div class="flex items-center justify-between pb-2 border-b border-slate-800">
                  <span class="font-black uppercase tracking-wider text-slate-200 text-xs flex items-center gap-1.5">
                    <Sliders class="w-4 h-4 text-amber-400" />
                    Practice Feature Toggles
                  </span>
                  <span class="text-[11px] text-slate-400">Customized for Valve CS2 Subtick</span>
                </div>

                <!-- TOGGLES GRID -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Grenade Trajectory Camera</span>
                      <span class="text-[10px] text-slate-400">PIP camera showing where grenade lands</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.grenadeCamera" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>

                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Pin-Pull Path Preview</span>
                      <span class="text-[10px] text-slate-400">Shows green trajectory arc while holding pin</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.grenadePreview" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>

                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Infinite Ammo & Grenades</span>
                      <span class="text-[10px] text-slate-400">Unlimited smokes, flashes, molotovs</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.infiniteAmmo" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>

                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Buy Anywhere & Anytime</span>
                      <span class="text-[10px] text-slate-400">Max money ($65k) with no buy zone limits</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.buyAnywhere" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>

                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Bullet Impact Boxes</span>
                      <span class="text-[10px] text-slate-400">Display client & server penetration hitboxes</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.showImpacts" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>

                  <label class="flex items-center justify-between p-3 bg-slate-950/80 border border-slate-800 rounded-xl cursor-pointer hover:border-slate-700 transition-colors">
                    <div class="flex flex-col">
                      <span class="font-bold text-white">Kick Bots Automatically</span>
                      <span class="text-[10px] text-slate-400">Removes bot interference immediately</span>
                    </div>
                    <input type="checkbox" v-model="cfgOptions.kickBots" class="w-4 h-4 accent-amber-500 rounded cursor-pointer" />
                  </label>
                </div>

                <!-- TRAIL DURATION SLIDER -->
                <div class="p-3 bg-slate-950/80 border border-slate-800 rounded-xl flex flex-col gap-1.5">
                  <div class="flex items-center justify-between text-xs">
                    <span class="font-bold text-white">Trajectory Trail Fade Duration:</span>
                    <span class="font-mono text-amber-400 font-bold">{{ cfgOptions.trajectoryTrailTime }} Seconds</span>
                  </div>
                  <input 
                    type="range" 
                    min="1" 
                    max="60" 
                    v-model.number="cfgOptions.trajectoryTrailTime" 
                    class="w-full accent-amber-500 cursor-pointer"
                  />
                </div>

                <!-- KEYBINDS CONFIG -->
                <div class="flex flex-col gap-2.5 pt-2">
                  <span class="font-black uppercase tracking-wider text-slate-200 text-xs">
                    Custom Practice Keybinds
                  </span>
                  <div class="grid grid-cols-2 sm:grid-cols-3 gap-2">
                    <div class="flex flex-col gap-1 p-2.5 bg-slate-950/80 border border-slate-800 rounded-xl">
                      <span class="text-[10px] text-slate-400 font-bold">Noclip / Fly</span>
                      <input 
                        v-model="cfgOptions.bindNoclip" 
                        type="text" 
                        class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-center font-mono font-bold text-white uppercase focus:border-amber-500 focus:outline-none"
                      />
                    </div>

                    <div class="flex flex-col gap-1 p-2.5 bg-slate-950/80 border border-slate-800 rounded-xl">
                      <span class="text-[10px] text-slate-400 font-bold">Rethrow Last Nade</span>
                      <input 
                        v-model="cfgOptions.bindRethrow" 
                        type="text" 
                        class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-center font-mono font-bold text-white uppercase focus:border-amber-500 focus:outline-none"
                      />
                    </div>

                    <div class="flex flex-col gap-1 p-2.5 bg-slate-950/80 border border-slate-800 rounded-xl">
                      <span class="text-[10px] text-slate-400 font-bold">Clear All Smokes/Fires</span>
                      <input 
                        v-model="cfgOptions.bindClearNades" 
                        type="text" 
                        class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-center font-mono font-bold text-white uppercase focus:border-amber-500 focus:outline-none"
                      />
                    </div>

                    <div class="flex flex-col gap-1 p-2.5 bg-slate-950/80 border border-slate-800 rounded-xl">
                      <span class="text-[10px] text-slate-400 font-bold">Place Bot at Crosshair</span>
                      <input 
                        v-model="cfgOptions.bindPlaceBot" 
                        type="text" 
                        class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-center font-mono font-bold text-white uppercase focus:border-amber-500 focus:outline-none"
                      />
                    </div>

                    <div class="flex flex-col gap-1 p-2.5 bg-slate-950/80 border border-slate-800 rounded-xl col-span-2 sm:col-span-1">
                      <span class="text-[10px] text-slate-400 font-bold">Fast-Forward Time (5x)</span>
                      <input 
                        v-model="cfgOptions.bindFastForward" 
                        type="text" 
                        class="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-center font-mono font-bold text-white uppercase focus:border-amber-500 focus:outline-none"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <!-- RIGHT: LIVE CFG PREVIEW & ACTIONS -->
              <div class="lg:col-span-5 flex flex-col gap-3">
                <div class="flex items-center justify-between">
                  <span class="font-black uppercase tracking-wider text-slate-200 text-xs flex items-center gap-1.5">
                    <Code2 class="w-4 h-4 text-emerald-400" />
                    Generated practice.cfg
                  </span>
                  <span class="text-[10px] font-mono text-slate-400">{{ generatedCfgScript.split('\n').length }} lines</span>
                </div>

                <div class="relative flex-1 bg-slate-950 border border-slate-800 rounded-2xl p-3 overflow-hidden flex flex-col">
                  <textarea
                    readonly
                    :value="generatedCfgScript"
                    class="w-full h-64 lg:h-80 bg-transparent text-emerald-400 font-mono text-[11px] resize-none focus:outline-none scrollbar-thin leading-relaxed"
                  ></textarea>

                  <div class="pt-3 border-t border-slate-800/80 flex items-center gap-2">
                    <button
                      @click="copyToClipboard(generatedCfgScript, 'cfg')"
                      class="flex-1 py-2 bg-slate-900 hover:bg-slate-850 text-slate-200 font-bold rounded-xl text-xs transition-colors flex items-center justify-center gap-1.5 cursor-pointer border border-slate-800"
                    >
                      <Check v-if="copiedCfg" class="w-4 h-4 text-emerald-400" />
                      <Copy v-else class="w-4 h-4" />
                      <span>{{ copiedCfg ? 'Copied to Clipboard!' : 'Copy Script' }}</span>
                    </button>

                    <button
                      @click="handleDownloadCfg"
                      class="flex-1 py-2 font-black rounded-xl text-xs transition-all flex items-center justify-center gap-1.5 shadow-lg cursor-pointer hover:opacity-90"
                      :style="{ backgroundColor: themeStore.customAccentColor, color: '#020617' }"
                    >
                      <Download class="w-4 h-4" />
                      <span>Download practice.cfg</span>
                    </button>
                  </div>
                </div>

                <!-- HOW TO INSTALL HELPER -->
                <div class="p-3 bg-slate-950/60 border border-slate-800/80 rounded-2xl flex flex-col gap-1 text-[11px] text-slate-400">
                  <strong class="text-white flex items-center gap-1.5">
                    <HelpCircle class="w-3.5 h-3.5 text-amber-400" />
                    How to install & use in CS2:
                  </strong>
                  <p>
                    1. Save <code class="text-amber-300 font-mono">practice.cfg</code> into your CS2 folder:<br>
                    <code class="text-slate-300 font-mono text-[10px] break-all bg-slate-900 px-1 py-0.5 rounded">steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg\</code>
                  </p>
                  <p>
                    2. In CS2, launch an offline practice match and type <code class="text-emerald-400 font-mono">exec practice</code> in your console.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <!-- ============================================================ -->
          <!-- TAB 2: TELEPORT & SETPOS COORDINATE EXPORTER -->
          <!-- ============================================================ -->
          <div v-else-if="activeTab === 'setpos'" class="flex flex-col gap-5">
            <div class="p-4 bg-slate-950/80 border border-slate-800 rounded-2xl flex flex-col gap-3">
              <div class="flex items-center justify-between">
                <span class="font-black uppercase tracking-wider text-white text-xs flex items-center gap-1.5">
                  <Sliders class="w-4 h-4 text-amber-400" />
                  Interactive In-Game Teleport Coordinate Generator
                </span>
                <span class="text-[10px] font-mono text-slate-400">Hammer World Units Precision</span>
              </div>
              <p class="text-slate-300 text-xs">
                Select any active map and any saved grenade lineup to instantly generate exact in-game console coordinates (<code class="text-amber-400 font-mono">setpos_exact</code>) to teleport directly to throw spots.
              </p>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <!-- MAP SELECTOR -->
              <div class="flex flex-col gap-1.5 p-3.5 bg-slate-950/80 border border-slate-800 rounded-2xl">
                <label class="font-bold text-slate-300">Choose Map:</label>
                <select 
                  v-model="selectedMapForSetpos"
                  class="bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white font-bold text-xs focus:outline-none focus:border-amber-500 cursor-pointer"
                >
                  <option v-for="map in mapStore.availableMaps" :key="map.id" :value="map.id">
                    {{ map.name }} ({{ map.code }})
                  </option>
                </select>
              </div>

              <!-- LINEUP SELECTOR -->
              <div class="flex flex-col gap-1.5 p-3.5 bg-slate-950/80 border border-slate-800 rounded-2xl">
                <label class="font-bold text-slate-300">Choose Lineup (Optional):</label>
                <select 
                  v-model="selectedLineupId"
                  class="bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-xs focus:outline-none focus:border-amber-500 cursor-pointer"
                >
                  <option value="">-- Map Center (Default Spawn) --</option>
                  <option v-for="l in availableLineupsForMap" :key="l.id" :value="l.id">
                    {{ l.title }} [{{ l.grenadeType.toUpperCase() }}] - {{ l.startLocation }} → {{ l.endLocation }}
                  </option>
                </select>
              </div>
            </div>

            <!-- OUTPUT CONSOLE COMMAND -->
            <div class="p-5 bg-black/90 border-2 border-amber-500/40 rounded-2xl flex flex-col gap-3 shadow-xl">
              <div class="flex items-center justify-between">
                <span class="font-mono font-black uppercase tracking-wider text-amber-400 text-xs flex items-center gap-2">
                  <Terminal class="w-4 h-4 text-amber-400 animate-pulse" />
                  CS2 Teleport Console Command (setpos_exact)
                </span>
                <span class="px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 font-mono text-[10px] font-bold">
                  Valve Standard Format
                </span>
              </div>

              <!-- HIGH VISIBILITY CONSOLE TERMINAL BOX -->
              <div class="flex flex-col sm:flex-row items-stretch sm:items-center gap-2.5 p-2 bg-slate-950 border border-slate-700/80 rounded-xl">
                <div class="flex items-center gap-2 flex-1 min-w-0 px-2 py-1">
                  <span class="text-emerald-400 font-mono font-black text-sm select-none">&gt;</span>
                  <input
                    type="text"
                    readonly
                    :value="currentSetposCommand"
                    @click="copyToClipboard(currentSetposCommand, 'setpos')"
                    class="flex-1 bg-transparent font-mono text-sm font-bold text-emerald-300 tracking-wide focus:outline-none cursor-pointer select-all truncate"
                    title="Click to select & copy"
                  />
                </div>

                <button
                  @click="copyToClipboard(currentSetposCommand, 'setpos')"
                  class="px-5 py-2.5 font-black text-xs rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg cursor-pointer hover:scale-[1.02] active:scale-95 shrink-0"
                  :style="{ backgroundColor: themeStore.customAccentColor, color: '#020617' }"
                >
                  <Check v-if="copiedSetpos" class="w-4 h-4 text-emerald-950 stroke-[3]" />
                  <Copy v-else class="w-4 h-4 stroke-[2.5]" />
                  <span class="tracking-wide">{{ copiedSetpos ? 'COPIED TO CLIPBOARD!' : 'COPY COMMAND' }}</span>
                </button>
              </div>

              <div class="flex items-center gap-2 text-[11px] text-slate-300 bg-slate-900/60 p-2.5 rounded-xl border border-slate-800">
                <span class="text-base">💡</span>
                <span>Open your CS2 in-game console with <kbd class="px-1.5 py-0.5 bg-slate-800 border border-slate-600 rounded text-amber-300 font-mono font-bold text-[10px]">~</kbd> and paste (<kbd class="px-1.5 py-0.5 bg-slate-800 border border-slate-600 rounded text-amber-300 font-mono font-bold text-[10px]">Ctrl + V</kbd>) to teleport directly to the throw spot.</span>
              </div>
            </div>
          </div>

          <!-- ============================================================ -->
          <!-- TAB 3: DEDICATED CS2 SERVER (WINDOWS PC & DOCKER / LXC HOSTING) -->
          <!-- ============================================================ -->
          <div v-else-if="activeTab === 'dedicated'" class="flex flex-col gap-5">
            
            <!-- PLATFORM SELECTOR -->
            <div class="flex items-center justify-between p-3.5 bg-slate-950/90 border border-slate-800 rounded-2xl flex-wrap gap-3">
              <div class="flex items-center gap-2.5">
                <div class="p-2 bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 rounded-xl">
                  <Server class="w-4 h-4" />
                </div>
                <div>
                  <h3 class="font-black text-xs text-white uppercase tracking-wider">
                    Select Server Hosting Environment
                  </h3>
                  <p class="text-[11px] text-slate-400">
                    Choose whether to run the dedicated server locally on your Windows Gaming PC or on a Linux Proxmox LXC.
                  </p>
                </div>
              </div>

              <div class="flex items-center gap-1.5 p-1 bg-slate-900 rounded-xl border border-slate-800">
                <button
                  @click="serverHostingPlatform = 'windows'"
                  :class="[
                    'px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5',
                    serverHostingPlatform === 'windows' ? 'bg-amber-500 text-slate-950 font-black shadow' : 'text-slate-400 hover:text-white'
                  ]"
                >
                  <Monitor class="w-3.5 h-3.5" />
                  <span>🪟 Windows PC (Local)</span>
                </button>
                <button
                  @click="serverHostingPlatform = 'docker'"
                  :class="[
                    'px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5',
                    serverHostingPlatform === 'docker' ? 'bg-cyan-500 text-slate-950 font-black shadow' : 'text-slate-400 hover:text-white'
                  ]"
                >
                  <Server class="w-3.5 h-3.5" />
                  <span>🐧 Linux Docker / Proxmox LXC</span>
                </button>
              </div>
            </div>

            <!-- ================= WINDOWS LOCAL HOSTING FLOW ================= -->
            <div v-if="serverHostingPlatform === 'windows'" class="flex flex-col gap-4">
              
              <!-- WARNING & SYSTEM IMPACT CARD -->
              <div class="p-4 bg-amber-500/10 border-2 border-amber-500/40 rounded-2xl flex flex-col gap-3">
                <div class="flex items-center gap-2 text-amber-400">
                  <ShieldAlert class="w-5 h-5 stroke-[2.5]" />
                  <span class="font-black uppercase tracking-wider text-xs">
                    ⚠️ Hardware & Performance Notice for Windows Local Hosting
                  </span>
                </div>

                <div class="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs text-slate-300">
                  <div class="p-2.5 bg-slate-950/70 rounded-xl border border-amber-500/20 flex flex-col gap-1">
                    <span class="font-black text-amber-300 flex items-center gap-1">
                      <Cpu class="w-3.5 h-3.5" /> RAM: 16 GB+ Required
                    </span>
                    <span class="text-[10px] text-slate-400">
                      CS2 Dedicated Server uses ~4-6 GB RAM. Running CS2 client + Server on same PC needs at least 16GB (32GB recommended).
                    </span>
                  </div>

                  <div class="p-2.5 bg-slate-950/70 rounded-xl border border-amber-500/20 flex flex-col gap-1">
                    <span class="font-black text-amber-300 flex items-center gap-1">
                      <Zap class="w-3.5 h-3.5" /> CPU / Subtick Load
                    </span>
                    <span class="text-[10px] text-slate-400">
                      Calculates full tickrate & physics in background. If you experience in-game FPS drops, consider singleplayer or Proxmox LXC.
                    </span>
                  </div>

                  <div class="p-2.5 bg-slate-950/70 rounded-xl border border-amber-500/20 flex flex-col gap-1">
                    <span class="font-black text-amber-300 flex items-center gap-1">
                      <FolderOpen class="w-3.5 h-3.5" /> ~35 GB Disk Space
                    </span>
                    <span class="text-[10px] text-slate-400">
                      SteamCMD downloads the standalone CS2 dedicated server binaries into <code class="text-amber-300 font-mono">C:\CS2_Dedicated_Server</code>.
                    </span>
                  </div>
                </div>

                <!-- APPROVAL CHECKBOX -->
                <label class="flex items-center gap-3 p-3 bg-slate-950/90 rounded-xl border border-amber-500/50 cursor-pointer select-none hover:bg-slate-900 transition-colors">
                  <input 
                    type="checkbox" 
                    v-model="approvedWindowsSelfInstall" 
                    class="w-5 h-5 accent-amber-500 rounded cursor-pointer shrink-0"
                  />
                  <div class="flex flex-col">
                    <span class="font-black text-white text-xs">
                      I understand the system impact and approve self-installing the CS2 Dedicated Server on this Windows PC.
                    </span>
                    <span class="text-[10px] text-slate-400">
                      Check this box to unlock 1-click installer scripts, automated SteamCMD setup, and server launchers.
                    </span>
                  </div>
                </label>
              </div>

              <!-- APPROVED WINDOWS INSTALLATION SUITE -->
              <div v-if="approvedWindowsSelfInstall" class="flex flex-col gap-4 animate-fade-in">
                
                <!-- SERVER CONFIGURATION INPUTS -->
                <div class="grid grid-cols-1 sm:grid-cols-4 gap-3">
                  <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                    <span class="text-[10px] text-slate-400 font-bold">Server Name:</span>
                    <input 
                      v-model="dedicatedConfig.serverName" 
                      type="text" 
                      class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-bold focus:border-amber-500 focus:outline-none"
                    />
                  </div>

                  <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                    <span class="text-[10px] text-slate-400 font-bold">Server Port:</span>
                    <input 
                      v-model.number="dedicatedConfig.serverPort" 
                      type="number" 
                      class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-mono focus:border-amber-500 focus:outline-none"
                    />
                  </div>

                  <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                    <span class="text-[10px] text-slate-400 font-bold">RCON Password:</span>
                    <input 
                      v-model="dedicatedConfig.rconPassword" 
                      type="text" 
                      class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-mono focus:border-amber-500 focus:outline-none"
                    />
                  </div>

                  <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                    <span class="text-[10px] text-slate-400 font-bold">Default Starting Map:</span>
                    <select 
                      v-model="dedicatedConfig.startMap" 
                      class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-bold focus:border-amber-500 focus:outline-none"
                    >
                      <option value="de_mirage">de_mirage</option>
                      <option value="de_dust2">de_dust2</option>
                      <option value="de_inferno">de_inferno</option>
                      <option value="de_nuke">de_nuke</option>
                      <option value="de_ancient">de_ancient</option>
                      <option value="de_anubis">de_anubis</option>
                      <option value="de_vertigo">de_vertigo</option>
                    </select>
                  </div>
                </div>

                <!-- 1-CLICK DOWNLOAD ACTION BUTTONS -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <!-- DOWNLOAD INSTALLER -->
                  <div class="p-4 bg-slate-950/90 border border-slate-800 rounded-2xl flex flex-col justify-between gap-3">
                    <div class="flex flex-col gap-1">
                      <span class="font-black text-xs text-white uppercase tracking-wide flex items-center gap-1.5">
                        <FileCode2 class="w-4 h-4 text-amber-400" />
                        1. Auto-Installer Batch Script
                      </span>
                      <p class="text-[11px] text-slate-400">
                        Automatically downloads SteamCMD, pulls CS2 binaries, creates directory structure, and writes practice.cfg.
                      </p>
                    </div>

                    <div class="flex items-center gap-2">
                      <button
                        @click="handleDownloadWindowsInstaller"
                        class="flex-1 px-4 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer shadow-lg"
                      >
                        <Download class="w-3.5 h-3.5 stroke-[2.5]" />
                        <span>Download install_cs2_server_windows.bat</span>
                      </button>

                      <button
                        @click="copyToClipboard(generatedWindowsInstallerScript, 'windowsInstaller')"
                        class="p-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 rounded-xl transition-colors cursor-pointer"
                        title="Copy Script"
                      >
                        <Check v-if="copiedWindowsInstaller" class="w-4 h-4 text-emerald-400" />
                        <Copy v-else class="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <!-- DOWNLOAD LAUNCHER -->
                  <div class="p-4 bg-slate-950/90 border border-slate-800 rounded-2xl flex flex-col justify-between gap-3">
                    <div class="flex flex-col gap-1">
                      <span class="font-black text-xs text-white uppercase tracking-wide flex items-center gap-1.5">
                        <Play class="w-4 h-4 text-emerald-400" />
                        2. Dedicated Server Startup Launcher
                      </span>
                      <p class="text-[11px] text-slate-400">
                        1-click launcher to start your CS2 dedicated server on port {{ dedicatedConfig.serverPort }} with your configured map & practice rules.
                      </p>
                    </div>

                    <div class="flex items-center gap-2">
                      <button
                        @click="handleDownloadWindowsStart"
                        class="flex-1 px-4 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer shadow-lg"
                      >
                        <Download class="w-3.5 h-3.5 stroke-[2.5]" />
                        <span>Download start_cs2_server.bat</span>
                      </button>

                      <button
                        @click="copyToClipboard(generatedWindowsStartScript, 'windowsStart')"
                        class="p-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 rounded-xl transition-colors cursor-pointer"
                        title="Copy Script"
                      >
                        <Check v-if="copiedWindowsStart" class="w-4 h-4 text-emerald-400" />
                        <Copy v-else class="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>

                <!-- SCRIPT PREVIEW BOX -->
                <div class="flex flex-col gap-2">
                  <span class="font-bold text-white text-xs">Self-Installer Script Source (install_cs2_server_windows.bat):</span>
                  <pre class="p-3.5 bg-slate-950 border border-slate-800 rounded-2xl font-mono text-[11px] text-amber-300 overflow-x-auto scrollbar-thin leading-relaxed max-h-48">{{ generatedWindowsInstallerScript }}</pre>
                </div>
              </div>

              <div v-else class="p-6 bg-slate-950/40 border border-slate-800/80 rounded-2xl flex flex-col items-center justify-center text-center gap-2">
                <AlertCircle class="w-8 h-8 text-slate-600" />
                <span class="text-xs font-bold text-slate-400">
                  Please review the hardware notice and check the approval box above to unlock the Windows Self-Installer package.
                </span>
              </div>

            </div>

            <!-- ================= DOCKER / PROXMOX LXC FLOW ================= -->
            <div v-else class="flex flex-col gap-4">
              <div class="p-4 bg-slate-950/80 border border-slate-800 rounded-2xl flex flex-col gap-2">
                <div class="flex items-center justify-between">
                  <span class="font-black uppercase tracking-wider text-white text-xs flex items-center gap-1.5">
                    <Server class="w-4 h-4 text-cyan-400" />
                    Host a 24/7 Dedicated CS2 Practice Server (Docker / Proxmox LXC)
                  </span>
                  <span class="text-[10px] font-mono text-emerald-400">Linux / Docker Compose</span>
                </div>
                <p class="text-slate-300 text-xs leading-relaxed">
                  Deploy a dedicated Counter-Strike 2 server on your Proxmox LXC (<code class="text-amber-400 font-mono">192.168.0.194</code>) or home server so your whole team can join with <code class="text-emerald-400 font-mono">connect &lt;IP&gt;:27015</code> and practice together.
                </p>
              </div>

              <!-- SERVER SETTINGS -->
              <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                  <span class="text-[10px] text-slate-400 font-bold">Server Name:</span>
                  <input 
                    v-model="dedicatedConfig.serverName" 
                    type="text" 
                    class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-bold focus:border-amber-500 focus:outline-none"
                  />
                </div>

                <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                  <span class="text-[10px] text-slate-400 font-bold">RCON Password:</span>
                  <input 
                    v-model="dedicatedConfig.rconPassword" 
                    type="text" 
                    class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-mono focus:border-amber-500 focus:outline-none"
                  />
                </div>

                <div class="flex flex-col gap-1 p-3 bg-slate-950/80 border border-slate-800 rounded-xl">
                  <span class="text-[10px] text-slate-400 font-bold">Default Starting Map:</span>
                  <select 
                    v-model="dedicatedConfig.startMap" 
                    class="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-white font-bold focus:border-amber-500 focus:outline-none"
                  >
                    <option value="de_mirage">de_mirage</option>
                    <option value="de_dust2">de_dust2</option>
                    <option value="de_inferno">de_inferno</option>
                    <option value="de_nuke">de_nuke</option>
                    <option value="de_ancient">de_ancient</option>
                    <option value="de_anubis">de_anubis</option>
                    <option value="de_vertigo">de_vertigo</option>
                  </select>
                </div>
              </div>

              <!-- DOCKER COMPOSE SNIPPET -->
              <div class="flex flex-col gap-2">
                <div class="flex items-center justify-between">
                  <span class="font-bold text-white text-xs">docker-compose.yml for your LXC:</span>
                  <button
                    @click="copyToClipboard(generatedDockerCompose, 'docker')"
                    class="px-3 py-1 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 text-xs font-bold rounded-lg transition-colors flex items-center gap-1.5 cursor-pointer"
                  >
                    <Check v-if="copiedDocker" class="w-3.5 h-3.5 text-emerald-400" />
                    <Copy v-else class="w-3.5 h-3.5" />
                    <span>{{ copiedDocker ? 'Copied!' : 'Copy Docker Compose' }}</span>
                  </button>
                </div>

                <pre class="p-3.5 bg-slate-950 border border-slate-800 rounded-2xl font-mono text-[11px] text-cyan-300 overflow-x-auto scrollbar-thin leading-relaxed">{{ generatedDockerCompose }}</pre>
              </div>
            </div>

          </div>

        </div>

        <!-- FOOTER -->
        <div class="p-4 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between shrink-0">
          <div class="flex items-center gap-2 text-xs text-slate-400">
            <Sparkles class="w-4 h-4 text-amber-400" />
            <span>All configs fully compatible with CS2 (Subtick & Premier Maps)</span>
          </div>
          <button
            @click="emit('close')"
            class="px-5 py-2 bg-slate-800 hover:bg-slate-700 text-white font-bold rounded-xl text-xs transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>
